"""empty message

Revision ID: 141b97d749d5
Revises: 257ce8b80026
Create Date: 2026-09-15 14:23:56.025702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141b97d749d5'
down_revision = '257ce8b80026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
